### ISSUE TITLE
Original signal score file missing

### ISSUE THREAD

**Issue by vaishalising** [ruoqi-liu/LP-SDA#3]
Hi, I'm not able to find original signal score file in the repo.
When I created a folder named 'SignalScoresSource', I'm getting the following error:

Traceback (most recent call last):
  File "run.py", line 115, in <module>
    more_main()
  File "run.py", line 112, in more_main
    main(args)
  File "run.py", line 37, in main
    data = FAERSdata(args.input, args.method, args.year)
  File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in __init__
    Files = [Files[-1]]
IndexError: list index out of range

Please help.
Thanks in advance.

**Comment by ruoqi-liu** [comment]
> Hi, I'm not able to find original signal score file in the repo.
> When I created a folder named 'SignalScoresSource', I'm getting the following error:
> 
> Traceback (most recent call last):
> File "run.py", line 115, in
> more_main()
> File "run.py", line 112, in more_main
> main(args)
> File "run.py", line 37, in main
> data = FAERSdata(args.input, args.method, args.year)
> File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in **init**
> Files = [Files[-1]]
> IndexError: list index out of range
> 
> Please help.
> Thanks in advance.

Hi, 
as shown in line 9 of FAERSdata.py
`Files = os.listdir('%s/%s' % (directory, method))`
it will obtain the files under directory/method/. The "directory" name (bydefault) is "SignalScoresSource" and the "method" name is one of 'PRR05', 'ROR05', 'GPS', 'BCPNN'. 
In order to run the code, your local input file structure should be
```
LP-SDA
│   run.py
│   ...  
└───SignalScoresSource
│   └───PRR05
│       │   prr_04.csv # for example, PRR signal scores using FAERS data collected until 2004
│       │   prr_05.csv
│       │   ...
│   └───ROR05
│       │   ror_04.csv 
│       │   ror_05.csv
│       │   ...
│   ...
```
The data structure for each signal score file is (demo) 
```
| drug id | adr id | signal score
| 64564 | 2342 | 5.22
```
After having these computed signal score files, you should be able to run the experiments.

**Comment by vaishalising** [comment]
> > Hi, I'm not able to find original signal score file in the repo.
> > When I created a folder named 'SignalScoresSource', I'm getting the following error:
> > Traceback (most recent call last):
> > File "run.py", line 115, in
> > more_main()
> > File "run.py", line 112, in more_main
> > main(args)
> > File "run.py", line 37, in main
> > data = FAERSdata(args.input, args.method, args.year)
> > File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in **init**
> > Files = [Files[-1]]
> > IndexError: list index out of range
> > Please help.
> > Thanks in advance.
> 
> Hi,
> as shown in line 9 of FAERSdata.py
> `Files = os.listdir('%s/%s' % (directory, method))`
> it will obtain the files under directory/method/. The "directory" name (bydefault) is "SignalScoresSource" and the "method" name is one of 'PRR05', 'ROR05', 'GPS', 'BCPNN'.
> In order to run the code, your local input file structure should be
> 
> ```
> LP-SDA
> │   run.py
> │   ...  
> └───SignalScoresSource
> │   └───PRR05
> │       │   prr_04.csv # for example, PRR signal scores using FAERS data collected until 2004
> │       │   prr_05.csv
> │       │   ...
> │   └───ROR05
> │       │   ror_04.csv 
> │       │   ror_05.csv
> │       │   ...
> │   ...
> ```
> 
> The data structure for each signal score file is (demo)
> 
> ```
> | drug id | adr id | signal score
> | 64564 | 2342 | 5.22
> ```
> 
> After having these computed signal score files, you should be able to run the experiments.

Thanks for the reply.
Where can I find these PRR and ROR csvs?

**Comment by ruoqi-liu** [comment]
> > > Hi, I'm not able to find original signal score file in the repo.
> > > When I created a folder named 'SignalScoresSource', I'm getting the following error:
> > > Traceback (most recent call last):
> > > File "run.py", line 115, in
> > > more_main()
> > > File "run.py", line 112, in more_main
> > > main(args)
> > > File "run.py", line 37, in main
> > > data = FAERSdata(args.input, args.method, args.year)
> > > File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in **init**
> > > Files = [Files[-1]]
> > > IndexError: list index out of range
> > > Please help.
> > > Thanks in advance.
> > 
> > 
> > Hi,
> > as shown in line 9 of FAERSdata.py
> > `Files = os.listdir('%s/%s' % (directory, method))`
> > it will obtain the files under directory/method/. The "directory" name (bydefault) is "SignalScoresSource" and the "method" name is one of 'PRR05', 'ROR05', 'GPS', 'BCPNN'.
> > In order to run the code, your local input file structure should be
> > ```
> > LP-SDA
> > │   run.py
> > │   ...  
> > └───SignalScoresSource
> > │   └───PRR05
> > │       │   prr_04.csv # for example, PRR signal scores using FAERS data collected until 2004
> > │       │   prr_05.csv
> > │       │   ...
> > │   └───ROR05
> > │       │   ror_04.csv 
> > │       │   ror_05.csv
> > │       │   ...
> > │   ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The data structure for each signal score file is (demo)
> > ```
> > | drug id | adr id | signal score
> > | 64564 | 2342 | 5.22
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After having these computed signal score files, you should be able to run the experiments.
> 
> Thanks for the reply.
> Where can I find these PRR and ROR csvs?

I didn't upload these original files. They can be easily computed using the existing R package ([phvid](https://cran.r-project.org/web/packages/PhViD/index.html)) based on FAERS data.

**Comment by vaishalising** [comment]
> phvid
Thanks for the reply :)

**Comment by vaishalising** [comment]
> > > > Hi, I'm not able to find original signal score file in the repo.
> > > > When I created a folder named 'SignalScoresSource', I'm getting the following error:
> > > > Traceback (most recent call last):
> > > > File "run.py", line 115, in
> > > > more_main()
> > > > File "run.py", line 112, in more_main
> > > > main(args)
> > > > File "run.py", line 37, in main
> > > > data = FAERSdata(args.input, args.method, args.year)
> > > > File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in **init**
> > > > Files = [Files[-1]]
> > > > IndexError: list index out of range
> > > > Please help.
> > > > Thanks in advance.
> > > 
> > > 
> > > Hi,
> > > as shown in line 9 of FAERSdata.py
> > > `Files = os.listdir('%s/%s' % (directory, method))`
> > > it will obtain the files under directory/method/. The "directory" name (bydefault) is "SignalScoresSource" and the "method" name is one of 'PRR05', 'ROR05', 'GPS', 'BCPNN'.
> > > In order to run the code, your local input file structure should be
> > > ```
> > > LP-SDA
> > > │   run.py
> > > │   ...  
> > > └───SignalScoresSource
> > > │   └───PRR05
> > > │       │   prr_04.csv # for example, PRR signal scores using FAERS data collected until 2004
> > > │       │   prr_05.csv
> > > │       │   ...
> > > │   └───ROR05
> > > │       │   ror_04.csv 
> > > │       │   ror_05.csv
> > > │       │   ...
> > > │   ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The data structure for each signal score file is (demo)
> > > ```
> > > | drug id | adr id | signal score
> > > | 64564 | 2342 | 5.22
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After having these computed signal score files, you should be able to run the experiments.
> > 
> > 
> > Thanks for the reply.
> > Where can I find these PRR and ROR csvs?
> 
> I didn't upload these original files. They can be easily computed using the existing R package ([phvid](https://cran.r-project.org/web/packages/PhViD/index.html)) based on FAERS data.

If possible can you please upload the csvs as well?

**Comment by ruoqi-liu** [comment]
> > > > > Hi, I'm not able to find original signal score file in the repo.
> > > > > When I created a folder named 'SignalScoresSource', I'm getting the following error:
> > > > > Traceback (most recent call last):
> > > > > File "run.py", line 115, in
> > > > > more_main()
> > > > > File "run.py", line 112, in more_main
> > > > > main(args)
> > > > > File "run.py", line 37, in main
> > > > > data = FAERSdata(args.input, args.method, args.year)
> > > > > File "/Users/user/Downloads/LP-SDA-master/FAERSdata.py", line 12, in **init**
> > > > > Files = [Files[-1]]
> > > > > IndexError: list index out of range
> > > > > Please help.
> > > > > Thanks in advance.
> > > > 
> > > > 
> > > > Hi,
> > > > as shown in line 9 of FAERSdata.py
> > > > `Files = os.listdir('%s/%s' % (directory, method))`
> > > > it will obtain the files under directory/method/. The "directory" name (bydefault) is "SignalScoresSource" and the "method" name is one of 'PRR05', 'ROR05', 'GPS', 'BCPNN'.
> > > > In order to run the code, your local input file structure should be
> > > > ```
> > > > LP-SDA
> > > > │   run.py
> > > > │   ...  
> > > > └───SignalScoresSource
> > > > │   └───PRR05
> > > > │       │   prr_04.csv # for example, PRR signal scores using FAERS data collected until 2004
> > > > │       │   prr_05.csv
> > > > │       │   ...
> > > > │   └───ROR05
> > > > │       │   ror_04.csv 
> > > > │       │   ror_05.csv
> > > > │       │   ...
> > > > │   ...
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The data structure for each signal score file is (demo)
> > > > ```
> > > > | drug id | adr id | signal score
> > > > | 64564 | 2342 | 5.22
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > After having these computed signal score files, you should be able to run the experiments.
> > > 
> > > 
> > > Thanks for the reply.
> > > Where can I find these PRR and ROR csvs?
> > 
> > 
> > I didn't upload these original files. They can be easily computed using the existing R package ([phvid](https://cran.r-project.org/web/packages/PhViD/index.html)) based on FAERS data.
> 
> If possible can you please upload the csvs as well?

I uploaded one file under "SignalScoresSource/PRR05/prr05_14.csv", which is the signal scores computed by PRR using data up to 2014.
